mw: 2.0
md: 1.0
alpha: 0.001

Jb11: 0.01
Jb22: 0.01
Jb33: 0.01

Jbinv11: 100.0
Jbinv22: 100.0
Jbinv33: 100.0

rt1: -0.01
rt2: 0.0
rt3: 0.0


# TODO (CARLOS): in the near future, the configs should look like this for matrices
# i have to leave them as scalars for now to play nicely with jax and numpy
# Jb:
# - [0.01, 0, 0]
# - [0, 0.01, 0]
# - [0, 0, 0.01]

# Jbinv:
# - [100.0, 0, 0]
# - [0, 100.0, 0]
# - [0, 0, 100.0]