# problem
trajectory:
  inherit: problem.yaml

# solution method
method:
  inherit: method.yaml

# analysis
analysis:
  type: standalone
  compute_iters: false
  show_iters: false
  show_convergence: true
  show_weights: true
