fcns:
  penalties:
    penalty:       trajopt/methods/common/penalties.py:penalty_cost
    autotune:      trajopt/methods/common/penalties.py:autotune
    create_params: trajopt/methods/common/penalties.py:create_params
    update_params: trajopt/methods/common/penalties.py:update_params

hyperparams:
  penalties:
    default:
      norm: l1
      W:
        penalty: True
        autotune: False
        init: 1000.0
      dual:
        autotune: False
        init: 0.0
      vb: standard
      eps: [0.0001]
