# ===============================
# MODEL FUNCTIONS
# ===============================

fcns:
  lift_drag: ../reentry_3dof.py:lift_drag
  heat_rate: ../reentry_3dof.py:heat_rate
  dynamic_pressure: ../reentry_3dof.py:dynamic_pressure
  aero_load: ../reentry_3dof.py:aero_load
  dynamics: ../reentry_3dof.py:dynamics
  long_lat: ../reentry_3dof.py:long_lat
  long_lat_alt: ../reentry_3dof.py:long_lat_alt
  density_model: ../reentry_3dof.py:exp_density
  altitude: ../reentry_3dof.py:altitude
  longitude: ../reentry_3dof.py:longitude
  latitude: ../reentry_3dof.py:latitude
  altitude_rate: ../reentry_3dof.py:altitude_rate
  velocity: ../reentry_3dof.py:velocity
  fpa: ../reentry_3dof.py:fpa
  heading: ../reentry_3dof.py:heading
  bank: ../reentry_3dof.py:bank
  aoa: ../reentry_3dof.py:aoa
  nonlinear_aero: ../reentry_3dof.py:nonlinear_aero

# ===============================
# STATE AND CONTROL CONFIG
# ===============================

state.r:
    idx: [0]
    scale: 10000
state.theta:
    idx: [1]
    scale: 1.0
state.phi:
    idx: [2]
    scale: 1.0
state.v:
    idx: [3]
    scale: 1000
state.gamma:
    idx: [4]
    scale: 1.0
state.psi:
    idx: [5]
    scale: 1.0

control.bank:
    idx: [0]
    scale: 1.0
control.aoa:
    idx: [1]
    scale: 1.0

time.scale: 100.0

# ===============================
# TRAJECTORIES FOR PLOTTING
# ===============================

trajectories:
  altitude:
    type: time_series
    fcn: "fcns.altitude * 0.001"
    group: state
    title: "Altitude vs Time"
    xlabel: "Time (s)"
    ylabel: "Altitude (km)"

  longitude:
    type: time_series
    fcn: fcns.longitude
    group: state
    title: "Longitude vs Time"
    xlabel: "Time (s)"
    ylabel: "Longitude (deg)"

  latitude:
    type: time_series
    fcn: fcns.latitude
    group: state
    title: "Latitude vs Time"
    xlabel: "Time (s)"
    ylabel: "Latitude (deg)"

  velocity:
    type: time_series
    fcn: fcns.velocity
    group: state
    title: "Velocity vs Time"
    xlabel: "Time (s)"
    ylabel: "Velocity (m/s)"

  fpa:
    type: time_series
    fcn: fcns.fpa
    group: state
    title: "Flight Path Angle vs Time"
    xlabel: "Time (s)"
    ylabel: "Flight Path Angle (deg)"

  heading:
    type: time_series
    fcn: fcns.heading
    group: state
    title: "Heading Angle vs Time"
    xlabel: "Time (s)"
    ylabel: "Heading Angle (deg)"

  bank_angle:
    type: time_series
    fcn: fcns.bank
    group: control
    title: "Bank Angle vs Time"
    xlabel: "Time (s)"
    ylabel: "Bank Angle (deg)"

  angle_of_attack:
    type: time_series
    fcn: fcns.aoa
    group: control
    title: "Angle of Attack vs Time"
    xlabel: "Time (s)"
    ylabel: "Angle of Attack (deg)"

  long_lat_trajectory_plot:
    type: spatial
    fcn: fcns.long_lat
    group: state_trajplots
    title: "Longitude vs Latitude"
    xlabel: "Longitude (deg)"
    ylabel: "Latitude (deg)"
    tick_nbins: 4
  
  long_lat_alt_trajectory_plot:
    type : spatial
    fcn: "fcns.long_lat_alt * [1, 1, 0.001]"
    group: state_trajplots
    title: "3D Trajectory"
    xlabel: "Longitude (deg)"
    ylabel: "Latitude (deg)"
    zlabel: "Altitude (km)"
    tick_nbins: 4

  heat_rate:
    type: time_series
    fcn: "fcns.heat_rate"
    group: path
    title: "Heat Rate vs Time"
    xlabel: "Time (s)"
    ylabel: "Heat Rate (W/cm²)"

  dynamic_pressure:
    type: time_series
    fcn: "fcns.dynamic_pressure"
    group: path
    title: "Dynamic Pressure vs Time"
    xlabel: "Time (s)"
    ylabel: "Dynamic Pressure (kPa)"

  aero_load:
    type: time_series
    fcn: "fcns.aero_load"
    group: path
    title: "Aerodynamic Load vs Time"
    xlabel: "Time (s)"
    ylabel: "Aerodynamic Load (g)"
