inherit: trajopt/methods/configs/autoscvx.yaml

penalty:
  nonconvex_inequality:
    W:
      penalty: True
      autotune: True
      init: 1.0
      eps_floor: 0.000001
      fac_eps: 0.3
      fac_target: 0.001
    
    dual: 
      penalty: True
      autotune: True
      init: 0.0
      beta: 1.0
    
    vb: 'standard'
    eps: [0.01]
    ct: False

  convex_inequality:
    W:
      penalty: False
      autotune: False
      init: 0.0
      eps_floor: 0.000001
      fac_eps: 0.3
      fac_target: 0.001
    dual: 
      penalty: False
      autotune: False
      init: 0.0
      beta: 1.0
    
    vb: 'standard'
    eps: [0.01]
    ct: False
  
  dynamics:
    W:
      penalty: False
      autotune: False
      init: 1.0
      eps_floor: 0.000001
      fac_eps: 0.3
      fac_target: 0.001
    dual: 
      penalty: False
      autotune: False
      init: 0.0
      beta: 1.0
    vb: 'standard'
    eps: [0.01]

  initial_state:
    W:
      penalty: False
      autotune: False
      init: 1.0
      eps_floor: 0.000001
      fac_eps: 0.3
      fac_target: 0.001
    dual: 
      penalty: False
      autotune: False
      init: 0.0
      beta: 1.0
    vb: 'standard'
    eps: [0.01]

  final_state:
    W:
      penalty: True
      autotune: True
      init: 1.0
      eps_floor: 0.000001
      fac_eps: 0.3
      fac_target: 0.001
    dual: 
      penalty: True
      autotune: True
      init: 0.0
      beta: 1.0
    vb: 'standard'
    eps: [0.01]

  state_limits:
    W:
      penalty: False
      autotune: False
      init: 1.0
      eps_floor: 0.000001
      fac_eps: 0.3
      fac_target: 0.001
    dual: 
      penalty: False
      autotune: False
      init: 0.0
      beta: 1.0
    vb: 'standard'
    eps: [0.01]

  control_limits:
    W:
      penalty: False
      autotune: False
      init: 1.0
      eps_floor: 0.000001
      fac_eps: 0.3
      fac_target: 0.001
    dual: 
      penalty: False
      autotune: False
      init: 0.0
      beta: 1.0
    vb: 'standard'
    eps: [0.01]

  final_time:
    W:
      penalty: False
      autotune: False
      init: 0.0
      eps_floor: 0.000001
      fac_eps: 0.3
      fac_target: 0.001
    dual: 
      penalty: False
      autotune: False
      init: 0.0
      beta: 1.0
    vb: 'none'
    eps: [0.01]