inherit: autoscvx-term.yaml

weights:
  alpha_z: 0.1
  alpha_nu: 0.1

penalty:
  final_state:
    W:
      init: 1000.0
  final_control:
    W:
      init: 1000.0
  final_nonconvex_equality:
    W:
      init: 1000.0

guess:
  type: propagation
