flags:
  auto_jac: 1
  auto_jac_aero: 1
  auto_jac_cnst: 1
  free_final_time: 0
  equal_dt: 0
  flag_conv: 0
  ode_fixed_dt: 0
  jax_dyn: 1
  ignore_dpp: 0
  ctcs: 0


# Convergence settings
conv:
  eps_cost:   []
  eps_state:  []
  eps_defect: 0.001
  eps_path:   []
  eps_nfz:    []
  eps_custom:    []
  eps_time:   0.001
  eps_term:   []
  eps_dyn:    []
  ctcs_mult_state: 1.0
  ctcs_mult_cnst: 1.0
  eps_ctcs: 0.000001
  iter_max: 300
  fac_eps: 0.0
  ctcs_fac_cnst: 0.5


time_grid: 40

solver_opts:
  solver: "CLARABEL"