inherit: scvx.yaml

flags:
  second_order: 1
  lm_adapt:     0
  min_eig_psd:  1.0e-6   # eigenvalue floor for the trust-region Hessian square root
  nsub:         3

penalty:
  default:
    dual:
      autotune: True
