flags:
  free_final_time:    1
  equal_dt:           1
  zoh_dilation:       1
  flag_conv:          1
  ignore_dpp:         0
  second_order:       1
  line_search:        1
  discretize: ms
  eps_state: [0.001]
  iter_max: 300

weights:
  alpha_z: 1.0
  alpha_nu: 1.0

penalty:
  default:
    norm: l1
    W:
      penalty: True
      autotune: False
      init: 1.0e3
    dual:
      penalty: True
      autotune: True
      init: 0.0
      beta: 1.0
    vb: standard
    eps: [0.0001]

solver_opts:
  solver: QOCO