method_class: dev.scvx_phases
formulation_class: dev.phases

inherit: autoscvx.yaml

flags:
  equal_dt: 0
  discretize: ps
  line_search: 1
  hp_segments: 10

# penalty:
#   initial_state:
#     vb: 'none'