method_class: dev.scp_phases
formulation_class: dev.phases

inherit:
  - autoscvx.yaml
  - trajopt/methods/common/configs/trust_region/second_order.yaml
  - trajopt/methods/common/configs/convexify/second_order.yaml
  - trajopt/methods/common/configs/discretize/second_order_ms.yaml
