method_class: dev.scp_phases
formulation_class: dev.phases

inherit:
  - scvx.yaml
  - trajopt/methods/common/configs/trust_region/second_order.yaml
  - trajopt/methods/common/configs/convexify/second_order.yaml
  - trajopt/methods/common/configs/discretize/second_order_ms.yaml

hyperparams:
  discretize:
    nsub: 3
  trust_region:
    lm_adapt:     0
    min_eig_psd:  1.0e-6   # eigenvalue floor for the trust-region Hessian square root
  penalties:
    default:
      dual:
        autotune: True
