# ===============================
# PARAMETERS
# ===============================
params:
  gamma_gs: 60
  g: 9.81
  rs: 4.5
  ls: 50.0
  mass: 120000
  Isp: 330
  lcg: "${0.4 * ls}"
  lcp: "${0.45 * ls}"
  J: "${1 / 12 * mass * (6 * rs**2 + ls**2)}"
  vterm: 85
  cd: "${1.2 * mass * g / (vterm**2)}"
  alpha: "${-1 / (Isp * g)}"