# source: https://underactuated.mit.edu/trajopt.html#perching
method:
  inherit: method.yaml
trajectory:
  inherit: problem.yaml
analysis:
  type: standalone
  compute_iters: true
  show_iters: true
  show_convergence: true
  show_weights: true
