# source: https://github.com/UW-ACL/SCPToolbox.jl/tree/master/test/examples/starship_flip

trajectory:
  inherit: problem.yaml
method:
  inherit: method.yaml
analysis:
  type: standalone
  compute_iters: false
  show_iters: false
  show_convergence: false
  show_weights: false
