# mission yaml for lander mission

planet: nondim_planet
vehicle: mikilander

constraint_params:
- name: dynamics

- name: initial_state
  x: [4, 4, 0, 0.0 , -4.0, 4.0, 0, 0, 0]
  x_idx: [1, 2, 3, 4, 5, 6, 11, 12, 13]

- name: final_state
  x: [0, 0, 0, 0, 0, 0, 1.0, 0, 0, 0, 0, 0, 0]
  x_idx: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  eps: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

- name: gimbal_limit
  theta_max: 20

- name: max_thrust
  max_val: 5

- name: min_thrust_norm
  params: {"min_thrust": 0.3}
  eps: [0.001]

- name: state_box
  x_min: [1.0]
  x_min_idx: [0]
  x_max: []
  x_max_idx: []

- name: glide_slope
  theta_max: 45

- name: tilt_limit
  theta_max: 90

- name: height_triggered_pitch
  params: {"cos_theta_max": 0.9, "trigger_height": 2.0}
  eps: [0.001]

cost_params:
- name: min_time