fcns:
  discretize:
    propagate_rk4: trajopt/methods/common/discretize.py:propagate_rk4
    make_node_propagation_solver: trajopt/methods/common/discretize.py:make_node_propagation_solver
    make_trajectory_solver: trajopt/methods/common/discretize.py:make_trajectory_solver
    propagate_from_nodes: trajopt/methods/common/discretize.py:propagate_from_nodes
    propagate_trajectory: trajopt/methods/common/discretize.py:propagate_trajectory
    differential_operator: null
    hp_operator: null

    create_time_params: trajopt/methods/common/discretize.py:create_time_params_ms
    update_time_params: trajopt/methods/common/discretize.py:update_time_params_ms
    create_time_constraints: trajopt/methods/common/discretize.py:create_time_constraints_ms
    final_time_interval_constraints: trajopt/methods/common/discretize.py:final_time_interval_constraints_ms

    dynamics_compile: trajopt/methods/common/discretize.py:dynamics_compile_ms
    dynamics_create_cvxpy_parameters: trajopt/methods/common/discretize.py:dynamics_create_cvxpy_parameters_ms
    dynamics_create_cvxpy_constraints: trajopt/methods/common/discretize.py:dynamics_create_cvxpy_constraints_ms
    dynamics_update_cvxpy_parameters: trajopt/methods/common/discretize.py:dynamics_update_cvxpy_parameters_ms
    dynamics_update_current_iter_data: trajopt/methods/common/discretize.py:dynamics_update_current_iter_data_ms

hyperparams:
  discretize:
    mode: ms
    nsub: 10                   # RK4 substeps per multiple-shooting interval
