method_class: dev.scp_phases
formulation_class: dev.phases

inherit:
  - autoscvx.yaml
  - trajopt/methods/common/configs/initial_guess/propagation.yaml

hyperparams:
  penalties:
    dynamics:
      vb: none
    final_state:
      vb: standard
