# MSRL multiphase EDL: guided entry, parachute descent, powered descent

trajectory:
  inherit: problem.yaml
method:
  inherit: method.yaml
analysis:
  type: standalone
  compute_iters: false
  show_iters: false
  show_convergence: true
  show_weights: false
